# Generated by Django 3.2.2 on 2021-05-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedtag',
            name='date_added',
        ),
    ]
