# Generated by Django 3.2.2 on 2021-05-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_linkedtag_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
