# Generated by Django 3.2.2 on 2021-05-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assetquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetquestion',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
