# Generated by Django 3.2.2 on 2021-05-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_assetquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='affiliate_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
