# Generated by Django 3.2.2 on 2021-05-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_asset_affiliate_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(related_name='assets', through='api.LinkedTag', to='api.Tag'),
        ),
    ]
