# Generated by Django 3.2.2 on 2021-05-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_asset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
