# Generated by Django 3.2.2 on 2021-06-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210521_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='short_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_daily_rate_limit',
            field=models.IntegerField(default=2000),
        ),
    ]
