# Generated by Django 3.2.2 on 2021-06-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_asset_tweb_url_clickthrogh_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='og_image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
