# Generated by Django 3.2.4 on 2021-06-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_asset_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('plan_summary', models.CharField(blank=True, max_length=1024, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price', models.CharField(blank=True, max_length=16, null=True)),
                ('per', models.CharField(blank=True, max_length=32, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, help_text='Optional link to page with more information (for clickable pricing table headers)', null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_plans', to='api.asset')),
            ],
            options={
                'verbose_name': 'Price Plan',
                'verbose_name_plural': 'Price Plans',
            },
        ),
    ]
