# Generated by Django 3.2.4 on 2021-06-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_priceplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceplan',
            old_name='plan_summary',
            new_name='summary',
        ),
    ]
