# Generated by Django 3.2.4 on 2021-07-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210627_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='name',
            field=models.CharField(help_text='Name of the Price Plan', max_length=128),
        ),
    ]
