# Generated by Django 3.2.4 on 2021-07-02 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_assetupvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=True)),
                ('upvoted_on', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.asset')),
                ('upvote_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web Service Vote',
                'verbose_name_plural': 'Web Service Votes',
            },
        ),
        migrations.DeleteModel(
            name='AssetUpvote',
        ),
    ]
