# Generated by Django 3.2.4 on 2021-07-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210702_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetvote',
            old_name='upvote_by',
            new_name='vote_by',
        ),
        migrations.RenameField(
            model_name='assetvote',
            old_name='upvoted_on',
            new_name='voted_on',
        ),
    ]
