# Generated by Django 3.2.4 on 2021-07-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210702_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetvote',
            old_name='vote_by',
            new_name='user',
        ),
    ]
