# Generated by Django 3.2.4 on 2021-07-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_vote_by_assetvote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetvote',
            name='upvote',
            field=models.BooleanField(default=True, help_text='Whether this is an Upvote=true (or Downvote=false)'),
        ),
    ]
