# Generated by Django 3.2.4 on 2021-07-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_assetvote_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceplan',
            name='url',
        ),
        migrations.AddField(
            model_name='asset',
            name='pricing_url',
            field=models.URLField(blank=True, help_text='Optional link to page with more information (for clickable pricing table headers)', null=True),
        ),
    ]
