# Generated by Django 3.2.4 on 2021-07-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210707_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
