# Generated by Django 3.2.4 on 2021-07-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210710_1744'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assetvote',
            constraint=models.UniqueConstraint(fields=('asset', 'user'), name='user_asset_vote'),
        ),
    ]
