# Generated by Django 3.2.4 on 2021-07-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210729_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Web Service Attribute', 'verbose_name_plural': 'Web Service Attributes'},
        ),
    ]
