# Generated by Django 3.2.4 on 2021-07-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_attribute_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevote',
            options={'verbose_name': 'Web Service Attribute Vote', 'verbose_name_plural': 'Web Service Attribute Votes'},
        ),
    ]
