# Generated by Django 3.2.6 on 2021-08-17 19:25

import api.models.tag
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_attributevote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='counter',
            field=models.BigIntegerField(default=0, validators=[api.models.tag.validate_positive_number]),
        ),
    ]
