# Generated by Django 3.2.6 on 2021-08-19 22:19

import api.models.asset
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210817_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.asset._upload_to_for_logos),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars/'),
        ),
    ]
