# Generated by Django 3.2.6 on 2021-08-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20210819_2219'),
        ('api', '0037_auto_20210820_0245'),
    ]

    operations = [
    ]
