# Generated by Django 3.2.6 on 2021-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_0037_auto_20210819_2219_0037_auto_20210820_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='avg_rating',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
