# Generated by Django 3.2.6 on 2021-08-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210821_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='has_free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
