# Generated by Django 3.2.6 on 2021-08-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_asset_upvotes_count'),
        ('api', '0041_auto_20210824_2041'),
    ]

    operations = [
    ]
