# Generated by Django 3.2.6 on 2021-08-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20210828_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetquestion',
            old_name='upvote_count',
            new_name='upvotes_count',
        ),
    ]
