# Generated by Django 3.2.6 on 2021-09-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_user_is_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetreview',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
