# Generated by Django 3.2.6 on 2021-09-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_claimasset_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimasset',
            options={'verbose_name': 'Web Service Claim Request', 'verbose_name_plural': 'Web Service Claim Requests'},
        ),
    ]
