# Generated by Django 3.2.6 on 2021-10-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_claimasset_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAssetLink',
            new_name='UserAssetUsage',
        ),
        migrations.RemoveConstraint(
            model_name='userassetusage',
            name='user_asset_link',
        ),
        migrations.AddConstraint(
            model_name='userassetusage',
            constraint=models.UniqueConstraint(fields=('user', 'asset'), name='user_asset_usage'),
        ),
    ]
