# Generated by Django 3.2.6 on 2021-10-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20211003_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='most_popular',
            field=models.BooleanField(default=False),
        ),
    ]
