# Generated by Django 3.2.6 on 2021-10-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_priceplan_most_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetquestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
