# Generated by Django 3.2.6 on 2021-10-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_assetquestion_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
