# Generated by Django 3.2.6 on 2021-10-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_rename_assets_user_used_assets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeVote',
            new_name='AssetAttributeVote',
        ),
    ]
