# Generated by Django 3.2.6 on 2021-10-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_rename_attributevote_assetattributevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
