# Generated by Django 3.2.6 on 2021-10-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_organization_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimasset',
            name='comment',
        ),
        migrations.AddField(
            model_name='claimasset',
            name='staff_comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='claimasset',
            name='user_comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
