# Generated by Django 3.2.6 on 2021-10-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20211017_0611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimAsset',
            new_name='AssetClaim',
        ),
    ]
