# Generated by Django 3.2.6 on 2021-10-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_rename_claimasset_assetclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetreview',
            name='video_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
