# Generated by Django 3.2.6 on 2021-10-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_assetreview_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_homepage_featured',
            field=models.BooleanField(default=False),
        ),
    ]
