# Generated by Django 3.2.6 on 2021-11-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_assetsolution_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetquestion',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
