# Generated by Django 3.2.6 on 2021-10-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_asset_is_homepage_featured'),
        ('api', '0065_alter_assetsolution_asset'),
    ]

    operations = []
