# Generated by Django 3.2.6 on 2021-11-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_merge_20211031_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_homepage_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
