# Generated by Django 3.2.6 on 2021-11-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_asset_is_homepage_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='trial_days',
            field=models.IntegerField(null=True),
        ),
    ]
