# Generated by Django 3.2.6 on 2021-11-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_asset_trial_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='trial_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
