# Generated by Django 3.2.6 on 2021-11-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20211101_2326'),
        ('api', '0070_tag_is_homepage_featured'),
    ]

    operations = [
    ]
