# Generated by Django 3.2.6 on 2021-11-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_merge_20211102_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_homepage_featured',
            field=models.BooleanField(default=False),
        ),
    ]
