# Generated by Django 3.2.6 on 2021-11-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_assetquestion_modified'),
        ('api', '0072_alter_tag_is_homepage_featured'),
    ]

    operations = [
    ]
