# Generated by Django 3.2.6 on 2021-11-08 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_tag_is_homepage_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='detailed_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='solution',
            name='follow_on_solutions',
            field=models.ManyToManyField(blank=True, related_name='upstream_solutions', to='api.Solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='follow_up_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='max_queue_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='solutionbooking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutionbooking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='eta_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='ETA Days'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='type',
            field=models.CharField(choices=[('I', 'Integration'), ('U', 'Usage Support'), ('O', 'Other')], default='I', max_length=2),
        ),
    ]
