# Generated by Django 3.2.6 on 2021-11-09 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_solutionbooking_provider_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetquestion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assetquestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 9, 3, 2, 18, 772653)),
            preserve_default=False,
        ),
    ]
