# Generated by Django 3.2.6 on 2021-11-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20211109_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionbooking',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='solutionbooking',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.solution'),
        ),
    ]
