# Generated by Django 3.2.6 on 2021-11-12 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20211112_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_primary', models.BooleanField(default=False)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.solution')),
            ],
            options={
                'verbose_name': 'Solution Price',
                'verbose_name_plural': 'Solution Prices',
            },
        ),
        migrations.AddConstraint(
            model_name='solutionprice',
            constraint=models.UniqueConstraint(fields=('solution', 'is_primary'), name='primary_price_of_solution'),
        ),
    ]
