# Generated by Django 3.2.6 on 2021-11-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20211112_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedSolutionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solution')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='tags',
            field=models.ManyToManyField(related_name='solutions', through='api.LinkedSolutionTag', to='api.Tag'),
        ),
    ]
