# Generated by Django 3.2.6 on 2021-11-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20211112_1555'),
        ('api', '0079_solution_primary_tag'),
    ]

    operations = [
    ]
