# Generated by Django 3.2.6 on 2021-11-15 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_merge_20211112_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='upvotes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SolutionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upvote', models.BooleanField(default=True, help_text='Whether this is an Upvote=true (or Downvote=false)')),
                ('voted_on', models.DateTimeField(auto_now_add=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_votes', to='api.solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solution Vote',
                'verbose_name_plural': 'Solution Votes',
            },
        ),
        migrations.AddConstraint(
            model_name='solutionvote',
            constraint=models.UniqueConstraint(fields=('solution', 'user'), name='user_solution_vote'),
        ),
    ]
