# Generated by Django 3.2.6 on 2021-11-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_solutionquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='has_free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
