# Generated by Django 3.2.6 on 2021-11-19 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_solution_has_free_trial'),
        ('api', '0083_solutionbooking_is_payment_completed'),
    ]

    operations = [
    ]
