# Generated by Django 3.2.6 on 2021-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_rename_has_free_trial_solution_has_free_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionbooking',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='solutionprice',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
