# Generated by Django 3.2.6 on 2021-11-29 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20211125_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionbooking',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_bookings', to='api.solution'),
        ),
    ]
