# Generated by Django 3.2.6 on 2021-12-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_solutionbooking_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='avg_rating',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solution',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
