# Generated by Django 3.2.6 on 2021-11-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_solutionbooking_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='bookings_pending_fulfillment_count',
            field=models.IntegerField(default=0),
        ),
    ]
