# Generated by Django 3.2.6 on 2021-12-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_auto_20211202_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1024, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.solution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solution Review',
                'verbose_name_plural': 'Solution Reviews',
            },
        ),
        migrations.AddConstraint(
            model_name='solutionreview',
            constraint=models.UniqueConstraint(fields=('solution', 'user'), name='user_solution_review'),
        ),
    ]
