# Generated by Django 3.2.6 on 2021-12-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_solution_bookings_pending_fulfillment_count'),
        ('api', '0091_auto_20211202_1541'),
    ]

    operations = [
    ]
