# Generated by Django 3.2.6 on 2021-12-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_merge_20211202_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='stripe_product_id',
        ),
        migrations.AlterField(
            model_name='solution',
            name='type',
            field=models.CharField(choices=[('I', 'Integration'), ('C', 'Consultation'), ('U', 'Usage Support'), ('O', 'Other')], default='I', max_length=2),
        ),
    ]
