# Generated by Django 3.2.6 on 2021-12-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('api', '0094_solution_stripe_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='pay_now_price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.price'),
        ),
    ]
