# Generated by Django 3.2.6 on 2021-12-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_solution_pay_now_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Software', 'verbose_name_plural': 'Softwares'},
        ),
        migrations.AlterModelOptions(
            name='assetattributevote',
            options={'verbose_name': 'Software Attribute Vote', 'verbose_name_plural': 'Software Attribute Votes'},
        ),
        migrations.AlterModelOptions(
            name='assetclaim',
            options={'verbose_name': 'Software Claim Request', 'verbose_name_plural': 'Software Claim Requests'},
        ),
        migrations.AlterModelOptions(
            name='assetreview',
            options={'verbose_name': 'Software Review', 'verbose_name_plural': 'Software Reviews'},
        ),
        migrations.AlterModelOptions(
            name='assetvote',
            options={'verbose_name': 'Software Vote', 'verbose_name_plural': 'Software Votes'},
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Software Attribute', 'verbose_name_plural': 'Software Attributes'},
        ),
    ]
