# Generated by Django 3.2.6 on 2021-12-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20211210_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolutionPrice',
        ),
    ]
