# Generated by Django 3.2.10 on 2021-12-17 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_delete_solutionprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionbooking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solutionbooking',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_solution_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solutionbooking',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.solution'),
        ),
    ]
