# Generated by Django 3.2.10 on 2021-12-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_delete_solutionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='consultation_scheduling_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
