# Generated by Django 3.2.10 on 2021-12-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_solution_consultation_scheduling_link'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solutionbooking',
            index=models.Index(fields=['booked_by'], name='booked_by_index'),
        ),
    ]
