# Generated by Django 3.2.6 on 2021-12-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_solution_consultation_scheduling_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
    ]
