# Generated by Django 3.2.6 on 2021-12-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_solution_is_searchable'),
        ('api', '0100_solutionbooking_booked_by_index'),
    ]

    operations = [
    ]
