# Generated by Django 3.2.10 on 2021-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_merge_20211222_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
