# Generated by Django 3.2.6 on 2021-12-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_merge_20211222_0933'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solutionreview',
            name='user_solution_review',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='solutionreview',
            name='content',
        ),
        migrations.RemoveField(
            model_name='solutionreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='solution',
            name='happy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='neutral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='sad_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solutionreview',
            name='type',
            field=models.CharField(choices=[('S', 'Sad'), ('N', 'Neutral'), ('H', 'Happy')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='solutionreview',
            constraint=models.UniqueConstraint(fields=('solution', 'user', 'type'), name='user_solution_review'),
        ),
    ]
