# Generated by Django 3.2.6 on 2021-12-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_alter_solution_slug'),
        ('api', '0102_auto_20211223_1342'),
    ]

    operations = [
    ]
