# Generated by Django 3.2.6 on 2021-12-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_alter_solutionreview_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solutionreview',
            name='user_solution_review',
        ),
        migrations.AddConstraint(
            model_name='solutionreview',
            constraint=models.UniqueConstraint(fields=('solution', 'user'), name='user_solution_review'),
        ),
    ]
