# Generated by Django 3.2.6 on 2021-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20211227_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionbooking',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
