# Generated by Django 3.2.10 on 2021-12-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_solutionbooking_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='is_searchable',
            field=models.BooleanField(default=True, help_text='Do we want this solution to show up in search results? (Or be like an unlisted link)'),
        ),
    ]
