# Generated by Django 3.2.6 on 2021-12-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_alter_solutionbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionbooking',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Completed', 'Completed')], default='Cancelled', max_length=15),
        ),
    ]
