# Generated by Django 3.2.10 on 2022-01-05 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_alter_solution_is_searchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='point_of_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
