# Generated by Django 3.2.10 on 2022-01-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_alter_solution_point_of_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solutionbooking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AddField(
            model_name='solutionbooking',
            name='rating',
            field=models.IntegerField(
                blank=True, choices=[(-1, '-1'), (0, '0'), (1, '1')], null=True
            ),
        ),
    ]
