# Generated by Django 3.2.10 on 2022-01-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20220108_2002'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='linkedsolution',
            constraint=models.UniqueConstraint(fields=('solution', 'asset'), name='unique_solution_asset_link'),
        ),
    ]
