# Generated by Django 3.2.6 on 2022-01-10 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_linkedsolution_unique_solution_asset_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionbooking',
            name='referring_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='booking_referring_user',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
