# Generated by Django 3.2.10 on 2022-01-15 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_user_stripe_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
                (
                    'searched_term',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'is_acknowledged',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this request has been addressed or not',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='user_problems',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'User Problem',
                'verbose_name_plural': 'User Problems',
            },
        ),
    ]
