# Generated by Django 3.2.10 on 2022-01-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_user_stripe_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedProblem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('problem_title', models.TextField()),
                (
                    'searched_term',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'is_acknowledged',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this request has been addressed or not',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Submitted Problem',
                'verbose_name_plural': 'Submitted Problems',
            },
        ),
    ]
