# Generated by Django 3.2.6 on 2022-01-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_alter_solution_billing_period'),
        ('api', '0114_userproblem'),
    ]

    operations = [
    ]
