# Generated by Django 3.2.11 on 2022-01-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_alter_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproblem',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
