# Generated by Django 3.2.11 on 2022-01-17 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('api', '0116_alter_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionbooking',
            name='stripe_subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
    ]
