# Generated by Django 3.2.11 on 2022-01-18 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_alter_userproblem_email'),
        ('api', '0117_solutionbooking_stripe_subscription'),
    ]

    operations = [
    ]
