# Generated by Django 3.2.11 on 2022-01-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_solution_primary_stripe_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='pay_now_price',
            new_name='stripe_primary_price',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='primary_stripe_price',
        ),
    ]
