# Generated by Django 3.2.11 on 2022-01-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20220119_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='promo_video',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
