# Generated by Django 3.2.11 on 2022-01-31 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_solution_promo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrackedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('tracked_hours', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('solution_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.solutionbooking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Tracked Day',
                'verbose_name_plural': 'Time Tracked Days',
            },
        ),
        migrations.AddConstraint(
            model_name='timetrackedday',
            constraint=models.UniqueConstraint(fields=('solution_booking', 'date'), name='booking_tracked_date'),
        ),
    ]
