# Generated by Django 3.2.11 on 2022-01-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_solution_promo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='og_image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
