# Generated by Django 3.2.11 on 2022-01-27 15:45

import api.models.solution
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_solution_promo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.solution._upload_to_for_cover_images),
        ),
    ]
