# Generated by Django 3.2.11 on 2022-02-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20220131_1902'),
        ('api', '0122_solution_cover_image'),
    ]

    operations = [
    ]
