# Generated by Django 3.2.11 on 2022-02-01 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_merge_20220131_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrackedday',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
