# Generated by Django 3.2.11 on 2022-02-02 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_alter_timetrackedday_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrackedday',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timetrackedday',
            name='solution_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solutionbooking'),
        ),
        migrations.AlterField(
            model_name='timetrackedday',
            name='tracked_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
