# Generated by Django 3.2.11 on 2022-02-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_auto_20220202_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionbooking',
            name='pause_status',
            field=models.CharField(choices=[('PROVIDER_PAUSED', 'PROVIDER_PAUSED'), ('CUSTOMER_PAUSED', 'CUSTOMER_PAUSED')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='solutionbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='Pending', max_length=15),
        ),
    ]
