# Generated by Django 3.2.11 on 2022-02-09 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('api', '0126_auto_20220206_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Price Plan', max_length=128)),
                ('summary', models.CharField(blank=True, max_length=1024, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price', models.CharField(blank=True, max_length=16, null=True)),
                ('per', models.CharField(blank=True, max_length=32, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('most_popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Price Plan',
                'verbose_name_plural': 'Price Plans',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='stripe_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.product'),
        ),
        migrations.DeleteModel(
            name='PricePlan',
        ),
        migrations.AddField(
            model_name='assetpriceplan',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_plans', to='api.asset'),
        ),
        migrations.AddField(
            model_name='assetpriceplan',
            name='stripe_price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.price'),
        ),
    ]
