# Generated by Django 3.2.11 on 2022-02-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('api', '0127_auto_20220209_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=150)),
                ('stripe_customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer')),
            ],
            options={
                'verbose_name': 'Partner Customer',
                'verbose_name_plural': 'Partner Customers',
            },
        ),
        migrations.AddConstraint(
            model_name='partnercustomer',
            constraint=models.UniqueConstraint(fields=('customer_id',), name='partner_customer'),
        ),
    ]
