# Generated by Django 3.2.11 on 2022-02-10 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('api', '0127_auto_20220209_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_uid', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.organization')),
                ('stripe_customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='djstripe.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPricePlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.thirdpartycustomer')),
                ('price_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.assetpriceplan')),
                ('stripe_subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='djstripe.subscription')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.AddConstraint(
            model_name='assetpriceplansubscription',
            constraint=models.UniqueConstraint(fields=('customer', 'price_plan'), name='customer_price_plan_subscription'),
        ),
    ]
