# Generated by Django 3.2.11 on 2022-02-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_auto_20220210_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirdpartycustomer',
            options={'verbose_name': 'Third Party Customer', 'verbose_name_plural': 'Third Party Customers'},
        ),
    ]
