# Generated by Django 3.2.11 on 2022-02-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_consultationrequest'),
        ('api', '0128_auto_20220210_0117'),
    ]

    operations = [
    ]
