# Generated by Django 3.2.11 on 2022-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_merge_20220210_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
