# Generated by Django 3.2.11 on 2022-02-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_auto_20220215_0305'),
        ('api', '0130_consultationrequest'),
    ]

    operations = [
    ]
