# Generated by Django 3.2.11 on 2022-02-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_alter_thirdpartycustomer_options'),
        ('api', '0130_alter_consultationrequest_customer_last_name'),
    ]

    operations = [
    ]
