# Generated by Django 3.2.12 on 2022-02-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_auto_20220216_0109'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='thirdpartycustomer',
            constraint=models.UniqueConstraint(fields=('customer_uid', 'organization'), name='third_party_organization_customer'),
        ),
    ]
