# Generated by Django 3.2.11 on 2022-02-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_thirdpartycustomer_third_party_organization_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_units', models.IntegerField(default=0)),
                ('usage_effective_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Customer Invoiced', 'Customer Invoiced')], default='Pending', max_length=17)),
                ('asset_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_subscriptions', to='api.assetpriceplansubscription')),
            ],
            options={
                'verbose_name': 'Asset Subscription Usage',
                'verbose_name_plural': 'Asset Subscription Usages',
            },
        ),
    ]
