# Generated by Django 3.2.12 on 2022-02-20 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_assetsubscriptionusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsubscriptionusage',
            name='usage_effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
