# Generated by Django 3.2.12 on 2022-02-21 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('api', '0134_alter_assetsubscriptionusage_usage_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartycustomer',
            name='stripe_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_customers', to='djstripe.customer'),
        ),
    ]
