# Generated by Django 3.2.12 on 2022-02-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_alter_assetsubscriptionusage_usage_effective_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('payment_method.attach', 'payment_method.attach'), ('payment_method.detach', 'payment_method.detach')], max_length=21)),
                ('receiver_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='registeredwebhook',
            constraint=models.UniqueConstraint(fields=('event_name', 'organization'), name='registered_webhook'),
        ),
    ]
